drop view speciesLinkDwC;

CREATE VIEW speciesLinkDwC AS
select	strain.last_update AS DateLastModified,
	'Fiocruz' AS InstitutionCode,
	strain.id_coll AS CollectionCode,
	strain.id_subcoll AS SubCollectionCode,
	strain.code AS CatalogNumber,
	replace(replace(replace(replace(scientific_names.sciname,'<b>',''),'<i>',''),'</b>',''),'</i>','') AS ScientificName,
	'L' AS BasisOfRecord,
	taxon_group_lang.taxon_group AS Kingdom,
	(select scientific_names_hierarchy.value AS value from scientific_names_hierarchy where ((scientific_names_hierarchy.id_sciname = species.id_sciname) and (scientific_names_hierarchy.id_hierarchy = 4))) AS Phylum,
	(select scientific_names_hierarchy.value AS value from scientific_names_hierarchy where ((scientific_names_hierarchy.id_sciname = species.id_sciname) and (scientific_names_hierarchy.id_hierarchy = 9))) AS Class,
	(select scientific_names_hierarchy.value AS value from scientific_names_hierarchy where ((scientific_names_hierarchy.id_sciname = species.id_sciname) and (scientific_names_hierarchy.id_hierarchy = 11))) AS  "Order",
	(select scientific_names_hierarchy.value AS value from scientific_names_hierarchy where ((scientific_names_hierarchy.id_sciname = species.id_sciname) and (scientific_names_hierarchy.id_hierarchy = 14))) AS Family,
	(select scientific_names_hierarchy.value AS value from scientific_names_hierarchy where ((scientific_names_hierarchy.id_sciname = species.id_sciname) and (scientific_names_hierarchy.id_hierarchy = 18))) AS Genus,
	(select scientific_names_hierarchy.value AS value from scientific_names_hierarchy where ((scientific_names_hierarchy.id_sciname = species.id_sciname) and (scientific_names_hierarchy.id_hierarchy = 21))) AS Species,
	(select scientific_names_hierarchy.value AS value from scientific_names_hierarchy where ((scientific_names_hierarchy.id_sciname = species.id_sciname) and (scientific_names_hierarchy.id_hierarchy = 22))) AS Subspecies,
	(select scientific_names_hierarchy.author from scientific_names_hierarchy inner join hierarchy_def on (scientific_names_hierarchy.id_hierarchy = hierarchy_def.id_hierarchy) where scientific_names_hierarchy.id_sciname = species.id_sciname and scientific_names_hierarchy.author is not null order by hierarchy_def.seq desc limit 1) AS ScientificNameAuthor,
	identifiedby.name AS IdentifiedBy,
	date_format(str_identification.date,'%Y') AS YearIdentified,
	date_format(str_identification.date,'%m') AS MonthIdentified,
	date_format(str_identification.date,'%d') AS DayIdentified,
	str_type_lang.type AS TypeStatus,
	NULL AS CollectorNumber,
	NULL AS FieldNumber,
	collector.name AS Collector,
	date_format(str_coll_event.date,'%Y') AS YearCollected,
	date_format(str_coll_event.date,'%m') AS MonthCollected,
	date_format(str_coll_event.date,'%d') AS DayCollected,
	NULL AS JulianDay,
	NULL AS TimeOfDay,
	NULL AS ContinentOcean,
	loc_country_lang.country AS Country,
	loc_state.state AS StateProvince,
	loc_city.city AS County,
	str_coll_event.place AS Locality,
	str_coll_event.gps_longitude AS Longitude,
	str_coll_event.gps_latitude AS Latitude,
	str_coll_event.gps_precision AS CoordinatePrecision,
	NULL AS BoundingBox,
	NULL AS MinimumElevation,
	NULL AS MaximumElevation,
	NULL AS MinimumDepth,
	NULL AS MaximumDepth,
	NULL AS Sex,
	NULL AS PreparationType,
	NULL AS IndividualCount,
	NULL AS PreviousCatalogNumber,
	str_host_name.host_name AS RelationshipType,
	NULL AS RelatedCatalogItem,
	str_cha_catalogue.catalogue_notes AS Notes,
	strain.history AS HistoryOfDeposit,
	depositor.name AS Depositor,
	date_format(str_deposit.date,'%Y') AS YearDeposited,
	date_format(str_deposit.date,'%m') AS MonthDeposited,
	date_format(str_deposit.date,'%d') AS DayDeposited,
	str_substratum.substratum AS Substrate,
	isolator.name AS Isolator,
	str_iso_method.iso_method AS IsolationMethod,
	concat_ws(' ','Temp:',str_culture.temp,'PH:',str_culture.ph) AS ConditionsForGrowth,
	strain.is_ogm AS GeneticallyModified,
	str_characs.genotypic AS Genotype,
	NULL AS Mutant,
	NULL AS Race,
	replace(replace(replace(replace(alternative_names.sciname_no_auth,'<b>',''),'<i>',''),'</b>',''),'</i>','') AS AlternateState,
	str_pro_properties.properties AS StrainProperties,
	str_pro_applications.applications AS StrainApplications,
	NULL AS FormOfSupply,
	str_cha_restrictions.restrictions AS Restrictions,
	str_cha_biorisk_comments.biorisk_comments AS BiologicalRisks,
	str_characs.pathogenic AS Pathogenicity
from ((((((((((((((((((((((((((((strain left join str_deposit on(((str_deposit.id_strain = strain.id_strain) and (str_deposit.id_coll = strain.id_coll)))) left join person depositor on((str_deposit.id_person = depositor.id_person))) left join species on((strain.id_species = species.id_species))) left join scientific_names on((species.id_sciname = scientific_names.id_sciname))) left join str_coll_event on(((str_coll_event.id_strain = strain.id_strain) and (str_coll_event.id_coll = strain.id_coll)))) left join person collector on((str_coll_event.id_person = collector.id_person))) left join str_identification on(((str_identification.id_coll = strain.id_coll) and (str_identification.id_strain = strain.id_strain)))) left join person identifiedby on((str_identification.id_person = identifiedby.id_person))) left join str_substratum on(((str_substratum.id_strain = strain.id_strain) and (str_substratum.id_coll = strain.id_coll) and (str_substratum.id_lang = 2)))) left join str_isolation on(((str_isolation.id_strain = strain.id_strain) and (str_isolation.id_coll = strain.id_coll)))) left join person isolator on((str_isolation.id_person = isolator.id_person))) left join str_iso_method on(((str_iso_method.id_strain = strain.id_strain) and (str_iso_method.id_coll = strain.id_coll) and (str_iso_method.id_lang = 2)))) left join str_culture on(((str_culture.id_strain = strain.id_strain) and (str_culture.id_coll = strain.id_coll)))) left join str_characs on(((str_characs.id_strain = strain.id_strain) and (str_characs.id_coll = strain.id_coll)))) left join str_pro_properties on(((str_pro_properties.id_strain = strain.id_strain) and (str_pro_properties.id_coll = strain.id_coll) and (str_pro_properties.id_lang = 2)))) left join str_pro_applications on(((str_pro_applications.id_strain = strain.id_strain) and (str_pro_applications.id_coll = strain.id_coll) and (str_pro_applications.id_lang = 2)))) left join str_cha_restrictions on(((str_cha_restrictions.id_strain = strain.id_strain) and (str_cha_restrictions.id_coll = strain.id_coll) and (str_cha_restrictions.id_lang = 2)))) left join str_cha_biorisk_comments on(((str_cha_biorisk_comments.id_strain = strain.id_strain) and (str_cha_biorisk_comments.id_coll = strain.id_coll) and (str_cha_biorisk_comments.id_lang = 2)))) left join str_cha_catalogue on(((str_cha_catalogue.id_strain = strain.id_strain) and (str_cha_catalogue.id_coll = strain.id_coll) and (str_cha_catalogue.id_lang = 2)))) left join str_host_name on(((str_host_name.id_strain = strain.id_strain) and (str_host_name.id_coll = strain.id_coll) and (str_host_name.id_lang = 2)))) left join taxon_group_lang on(((taxon_group_lang.id_taxon_group = species.id_taxon_group) and (taxon_group_lang.id_lang = 2)))) left join loc_country_lang on(((str_coll_event.id_country = loc_country_lang.id_country) and (loc_country_lang.id_lang = 2)))) left join loc_state on((str_coll_event.id_state = loc_state.id_state))) left join loc_city on((str_coll_event.id_city = loc_city.id_city))) left join species alternative on((species.id_alt_states = alternative.id_species))) left join scientific_names alternative_names on((alternative.id_sciname = alternative_names.id_sciname))) left join str_type_lang on(((strain.id_type = str_type_lang.id_type) and (str_type_lang.id_lang = 2)))) join roles_permissions rp on(((rp.id_item = strain.id_strain) and (rp.id_role = 1) and (rp.id_area = 2)))) where ((strain.go_catalog = 1) and (strain.status = 'active') and (str_deposit.id_dep_reason = 1));

