#! /usr/bin/env python
# -*- coding: utf-8 -*-

label_trace = {

#Fields
"Log Division": _("Log Division"),
"Log Strain Code": _("Log Strain Code"),
"Log Origin Code": _("Log Origin Code"),
"Log Status": _("Log Status"),
"Log Taxon": _("Log Taxon"),
"Log Type": _("Log Type"),
"Log Ogm": _("Log Ogm"),
"Log Taxonomic Complement": _("Log Taxonomic Complement"),
"Log History": _("Log History"),
"Log Codes in Other Collections": _("Log Codes in Other Collections"),
"Log General Comments": _("Log General Comments"),
"Log Collector Date": _("Log Collector Date"),
"Log Collector Person": _("Log Collector Person"),
"Log Collector Institution": _("Log Collector Institution"),
"Log Country": _("Log Country"),
"Log State": _("Log State"),
"Log City": _("Log City"),
"Log Place": _("Log Place"),
"Log Latitude": _("Log Latitude"),
"Log Latitude DMS": _("Log Latitude DMS"),
"Log Latitude Mode": _("Log Latitude Mode"),
"Log Longitude": _("Log Longitude"),
"Log Longitude DMS": _("Log Longitude DMS"),
"Log Longitude Mode": _("Log Longitude Mode"),
"Log Datum": _("Log Datum"),
"Log Precision": _("Log Precision"),
"Log GPS Comments": _("Log GPS Comments"),
"Log Substratum": _("Log Substratum"),
"Log Host Name": _("Log Host Name"),
"Log Host Genus": _("Log Host Genus"),
"Log Host Specie": _("Log Host Specie"),
"Log Host Level": _("Log Host Level"),
"Log Host Subspecie": _("Log Host Subspecie"),
"Log Host Taxonomic Complement": _("Log Host Taxonomic Complement"),
"Log Internation Code": _("Log Internation Code"),
"Log Clinical Form": _("Log Clinical Form"),
"Log Hiv": _("Log Hiv"),
"Log Collector Comments": _("Log Collector Comments"),
"Log Isolation Date": _("Log Isolation Date"),
"Log Isolation Person": _("Log Isolation Person"),
"Log Isolation Institution": _("Log Isolation Institution"),
"Log Isolation From": _("Log Isolation From"),
"Log Isolation Method": _("Log Isolation Method"),
"Log Isolation Comments": _("Log Isolation Comments"),
"Log Identification Date": _("Log Identification Date"),
"Log Identification Person": _("Log Identification Person"),
"Log Identification Institution": _("Log Identification Institution"),
"Log Identification Genus": _("Log Identification Genus"),
"Log Identification Specie": _("Log Identification Specie"),
"Log Identification Level": _("Log Identification Level"),
"Log Identification Subspecie": _("Log Identification Subspecie"),
"Log Identification Taxonomic Complement": _("Log Identification Taxonomic Complement"),
"Log Identification Method": _("Log Identification Method"),
"Log Identification Comments": _("Log Identification Comments"),
"Log Deposit Date": _("Log Deposit Date"),
"Log Deposit Person": _("Log Deposit Person"),
"Log Deposit Institution": _("Log Deposit Institution"),
"Log Deposit Genus": _("Log Deposit Genus"),
"Log Deposit Specie": _("Log Deposit Specie"),
"Log Deposit Leve": _("Log Deposit Leve"),
"Log Deposit Subspecie": _("Log Deposit Subspecie"),
"Log Deposit Taxonomic Complement": _("Log Deposit Taxonomic Complement"),
"Log Deposit Type": _("Log Deposit Type"),
"Log How Culture Was Sent": _("Log How Culture Was Sent"),
"Log Recommended Preservation Method": _("Log Recommended Preservation Method"),
"Log Autentication Date": _("Log Autentication Date"),
"Log Autentication Responsible": _("Log Autentication Responsible"),
"Log Autentication Result": _("Log Autentication Result"),
"Log Deposit Comments": _("Log Deposit Comments"),
"Log Recommended Culture Medium": _("Log Recommended Culture Medium"),
"Log Recommended Temperature": _("Log Recommended Temperature"),
"Log Incubation Time": _("Log Incubation Time"),
"Log PH": _("Log PH"),
"Log Oxygen Requirements": _("Log Oxygen Requirements"),
"Log Growth Comments": _("Log Growth Comments"),
"Log Morphological Characteristics": _("Log Morphological Characteristics"),
"Log Molecular Characteristics": _("Log Molecular Characteristics"),
"Log Biochemical Characteristics": _("Log Biochemical Characteristics"),
"Log Immunological Characteristics": _("Log Immunological Characteristics"),
"Log Pathogenic Characteristics": _("Log Pathogenic Characteristics"),
"Log Genotypic Characteristics": _("Log Genotypic Characteristics"),
"Log OGM Group": _("Log OGM Group"),
"Log OGM Comments": _("Log OGM Comments"),
"Log Biological Risk Comments": _("Log Biological Risk Comments"),
"Log Restrictions": _("Log Restrictions"),
"Log Pictures": _("Log Pictures"),
"Log Characteristics References": _("Log Characteristics References"),
"Log Additiona Notes to Catalog": _("Log Additiona Notes to Catalog"),
"Log Properties": _("Log Properties"),
"Log Applications": _("Log Applications"),
"Log Properties References": _("Log Properties References"),
"Log Stock": _("Log Stock"),
"Log Stock Movement Insert": _("Log Stock Movement Insert"),
"Log Stock Movement Delete": _("Log Stock Movement Delete"),
"Log Strain Goes to Catalog": _("Log Strain Goes to Catalog"),
"Log Preservation Date": _("Log Preservation Date"),
"Log Preservation Lot": _("Log Preservation Lot"),
"Log Preservation Responsible": _("Log Preservation Responsible"),
"Log Preservation Method": _("Log Preservation Method"),
"Log Process Data": _("Log Process Data"),
"Log Preservation Strain Origin": _("Log Preservation Strain Origin"),
"Log Preservation Strain Code": _("Log Preservation Strain Code"),
"Log Preservation Strain Lot": _("Log Preservation Strain Lot"),
"Log Preservation Strain Minimum Stock": _("Log Preservation Strain Minimum Stock"),
"Log Preservation Strain Culture Medium": _("Log Preservation Strain Culture Medium"),
"Log Preservation Strain Temperature": _("Log Preservation Strain Temperature"),
"Log Preservation Strain Incubation Time": _("Log Preservation Strain Incubation Time"),
"Log Preservation Strain Cryoprotector": _("Log Preservation Strain Cryoprotector"),
"Log Preservation Strain Type": _("Log Preservation Strain Type"),
"Log Preservation Strain Purity": _("Log Preservation Strain Purity"),
"Log Preservation Strain Couting": _("Log Preservation Strain Couting"),
"Log Preservation Strain Does Not Apply": _("Log Preservation Strain Does Not Apply"),
"Log Preservation Strain Macroscopic Characteristics": _("Log Preservation Strain Macroscopic Characteristics"),
"Log Preservation Strain Microscopic Characteristics": _("Log Preservation Strain Microscopic Characteristics"),
"Log Preservation Strain Results": _("Log Preservation Strain Results"),
"Log Presertavion Strain Observations": _("Log Presertavion Strain Observations"),
"Log Distribution Date": _("Log Distribution Date"),
"Log Distribution Responsible": _("Log Distribution Responsible"),
"Log Distribution Lot": _("Log Distribution Lot"),
"Log Distribution Institution": _("Log Distribution Institution"),
"Log Distribution Person": _("Log Distribution Person"),
"Log Distribution Reason": _("Log Distribution Reason"),
"Log QC Date": _("Log QC Date"),
"Log QC Responsible": _("Log QC Responsible"),
"Log QC Lot": _("Log QC Lot"),
"Log QC Tests": _("Log QC Tests"),
"Log QC Purity": _("Log QC Purity"),
"Log Used Test": _("Log Used Test"),

"original": _("Log Original"),
"lot": _("Log Lot"),
"n": _("Log N"),
"y": _("Log Y"),
"block": _("Log Block"),
"spore": _("Log Spore"),
"none": _("Log None"),
"active": _("Log Active"),
"inactive": _("Log Inactive"),
"pending": _("Log Pending"),
"yes": _("Log Yes"),
"no": _("Log No"),
"decimal": _("Log Decimal"),
"dms": _("Log Dms"),
"0": _("Log 0"),
"1": _("Log 1"),
"2": _("Log 2"),


#Operations
"Log Strain Insert": _("Log Strain Insert"),
"Log Strain Edit": _("Log Strain Edit"),
"Log Strain Delete": _("Log Strain Delete"),
"Log Taxon Edit": _("Log Taxon Edit"),
"Log Institution Edit": _("Log Institution Edit"),
"Log Person Edit": _("Log Person Edit"),
"Log Division Edit": _("Log Division Edit"),
"Log Preservation Insert": _("Log Preservation Insert"),
"Log Preservation Edit": _("Log Preservation Edit"),
"Log Preservation Delete": _("Log Preservation Delete"),
"Log Distribution Insert": _("Log Distribution Insert"),
"Log Distribution Edit": _("Log Distribution Edit"),
"Log Distribution Delete": _("Log Distribution Delete"),
"Log QC Insert": _("Log QC Insert"),
"Log QC Edit": _("Log QC Edit"),
"Log QC Delete": _("Log QC Delete"),

#Entities
"Log Strain": _("Log Strain"),
}

label_values_dict = {   
    
    "ogm":{"":"", "0":"label_ogm_0","1":"label_ogm_1","2":"label_ogm_2"},
    "is_ogm":{"":"", "0":"label_is_ogm_0","1":"label_is_ogm_1"},
    "go_catalog":{"":"", "1":"label_go_catalog_1", "0":"label_go_catalog_0"}
}

values_dict = {
                       "":"",    
    "label_ogm_0"        : _("Unknown"),
    "label_ogm_1"        : _("Group I"),
    "label_ogm_2"        : _("Group II"),
    "label_is_ogm_0"        : _("False"),
    "label_is_ogm_1"        : _("True"),
    "label_go_catalog_1" : _("True"),
    "label_go_catalog_0" : _("False")
}