#! /usr/bin/env python3
# -*- coding: utf-8 -*-

'''
This file contains a mapping from the labels found in the html
templates to translatable strings.
'''

label_dict = {

"label_Container": _("Container"),
"label_Rep_Division": _("Rep Division"),

#taxa
"label_Species_General_Comments": _("Comments"),
"label_Species_General_Hazard_Group_Comments": _("Comments"),
"label_Species_General_Author": _("Author"),
"label_Species_General_Species": _("singular|Species"),
"label_Species_General_Classification": _("Classification"),
"label_Species_General_Taxonomical_References": _("Taxonomic References"),
"label_Species_General_Synonym": _("Synonym"),
"label_Species_General_Hazard_Group": _("Hazard_Group"),
"label_Species_General_Reference": _("Reference"),
"label_Species_General_Alternative_State": _("Alternative State"),
"label_Species_General_Alternative_State_Type": _("Type"),
"label_Species_General_Scientific_Name": _("Scientific Name"),
"label_Species_General_Higher_Taxa": _("Higher Taxa"),
"label_Species_General_Taxonomic_Group": _("Taxonomic Group"),

#strains
"label_Strains_General_Code": _("Code"),
"label_Strains_General_Comments": _("Comments"),
"label_Strains_General_Species": _("singular|Species"),
"label_Strains_General_Division": _("Division"),
"label_Strains_General_Numeric_Code": _("Number"),
"label_Strains_General_Autonum": _("Auto Numeration"),
"label_Strains_General_Origin_Code" : _("Origin Code"),
"label_Strains_General_Taxonomic_Complement" : _("Taxonomic Complement"),
"label_Strains_General_Type" : _("Type"),
"label_Strains_General_Status" : _("Status"),
"label_Strains_General_Is_OGM" : _("OGM"),
"label_Strains_General_History" : _("History"),
"label_Strains_General_Codes_In_Other_Collections" : _("Codes in Other Collections"),
"label_Strains_Origin_Comments": _("Comments"),
"label_Strains_Origin_Origin_Place" : _("Origin Place"),
"label_Strains_Origin_Date" : _("Date"),
"label_Strains_Origin_Collector" : _("Collector"),
"label_Strains_Origin_Collector_Person" : _("Person"),
"label_Strains_Origin_Collector_Institution" : _("Institution"),
"label_Strains_Origin_Country" : _("Country"),
"label_Strains_Origin_State" : _("State"),
"label_Strains_Origin_City" : _("City"),
"label_Strains_Origin_Place" : _("Place"),
"label_Strains_Origin_GPS": _("GPS"),
"label_Strains_Origin_GPS_Latitude": _("Latitude"),
"label_Strains_Origin_GPS_Longitude" : _("Longitude"),
"label_Strains_Origin_GPS_Precision" : _("Precision"),
"label_Strains_Origin_GPS_Datum" : _("Datum"),
"label_Strains_Origin_GPS_Comments" : _("Comments"),
"label_Strains_Origin_Precision_Meters" :_("(m)"),
"label_Strains_Origin_Host": _("HOST"),
"label_Strains_Origin_Host_Common_Name": _("Common Name"),
"label_Strains_Origin_Host_Genus" : _("Genus"),
"label_Strains_Origin_Host_Infraespecific_Name": _("Infraespecific Name"),
"label_Strains_Origin_Host_Complement_Infraespecific": _("Taxonomic Complement"),
"label_Strains_Origin_Host_Level" : _("Level"),
"label_Strains_Origin_International_Code" : _("International Code"),
"label_Strains_Origin_Substratum" : _("Substratum"),
"label_Strains_Origin_Clinic_Form" : _("Clinic Form"),
"label_Strains_Origin_HIV" : _("HIV"),
"label_Strains_Origin_Specific_Epithet" : _("Specific Epithet"),
"label_Strains_Isolation_Comments": _("Comments"),
"label_Strains_Isolation_Date" : _("Date"),
"label_Strains_Isolation_Isolated_By" : _("Isolated by"),
"label_Strains_Isolation_Person" : _("Person"),
"label_Strains_Isolation_Institution" : _("Institution"),
"label_Strains_Isolation_Isolated_From": _("Isolated from"),
"label_Strains_Isolation_Method" : _("Method"),
"label_Strains_Identification_Comments": _("Comments"),
"label_Strains_Identification_Identified_As_Species" : _("Identified as"),
"label_Strains_Identification_Identified_Genus" : _("Genus"),
"label_Strains_Identification_Identified_Specie" : _("Specie"),
"label_Strains_Identification_Identified_Infraespecific_Name": _("Infraespecific Name"),
"label_Strains_Identification_Identified_Complement_Infraespecific": _("Taxonomic Complement"),
"label_Strains_Identification_Identified_Level" : _("Level"),
"label_Strains_Identification_Date" : _("Date"),
"label_Strains_Identification_Identified_By" : _("Identified by"),
"label_Strains_Identification_Person" : _("Person"),
"label_Strains_Identification_Institution" : _("Institution"),
"label_Strains_Identification_Method" : _("Method"),
"label_Strains_Deposit_Comments": _("Comments"),
"label_Strains_Deposit_Deposited_By_Person" : _("Person"),
"label_Strains_Deposit_Deposited_By_Institution" : _("Institution"),
"label_Strains_Deposit_Deposited_As_Species" : _("Deposited as"),
"label_Strains_Deposit_Deposited_By" : _("Deposited by"),
"label_Strains_Deposit_Authentication": _("Authentication"),
"label_Strains_Deposit_Authentication_Date": _("Date"),
"label_Strains_Deposit_Authentication_Person": _("Responsible"),
"label_Strains_Deposit_Authentication_Result": _("Result"),
"label_Strains_Deposit_Deposited_Genus" : _("Genus"),
"label_Strains_Deposit_Deposited_Infraespecific_Name": _("Infraespecific Name"),
"label_Strains_Deposit_Deposited_Complement_Infraespecific": _("Taxonomic Complement"),
"label_Strains_Deposit_Deposited_Level" : _("Level"),
"label_Strains_Deposit_Date" : _("Date"),
"label_Strains_Deposit_Reason" : _("Deposit Type"),
"label_Strains_Deposit_Recommended_Preservation_Method" : _("Recommended Preservation Method"),
"label_Strains_Deposit_Culture_Was_Sent" : _("How Culture was sent"),
"label_Strains_Deposit_Specific_Epithet" : _("Specific Epithet"),
"label_Strains_Growth_Comments": _("Comments"),
"label_Strains_Growth_Recommended_Culture_Medium" : _("Recommended Culture Medium"),
"label_Strains_Growth_Recommended_Temperature" : _("Recommended Temperature"),
"label_Strains_Growth_Incubation_Time" : _("Incubation Time"),
"label_Strains_Growth_Ph" : _("PH"),
"label_Strains_Growth_Oxygen_Requirements" : _("Oxygen Requirements"),
"label_Strains_Characteristics_Biochemical" : _("Biochemical"),
"label_Strains_Characteristics_Molecular" : _("Molecular"),
"label_Strains_Characteristics_Immunologic" : _("Immunological"),
"label_Strains_Characteristics_Morphologic" : _("Morphological"),
"label_Strains_Characteristics_Pathogenic" : _("Pathogenic"),
"label_Strains_Characteristics_Genotypic" : _("Genotypic"),
"label_Strains_Characteristics_OGM" : _("OGM"),
"label_Strains_Characteristics_OGM_Group" : _("Group"),
"label_Strains_Characteristics_OGM_Comments" : _("Comments"),
"label_Strains_Characteristics_Biological_Risk_Comments" : _("Biological Risk Comments"),
"label_Strains_Characteristics_Restrictions" : _("Restrictions"),
"label_Strains_Characteristics_Pictures" : _("Pictures"),
"label_Strains_Characteristics_URL" : _("References (links etc.)"),
"label_Strains_Characteristics_Additional_Notes_to_Catalog" : _("Additional Notes to Catalog"),
"label_Strains_Properties_Properties" : _("Properties"),
"label_Strains_Properties_Applications" : _("Applications"),
"label_Strains_Properties_URL" : _("References (links etc.)"),
"label_Strains_QC_Purity": _("Purity"),
"label_Strains_QC_Counting": _("Counting"),
"label_Strains_QC_Counting_Unity": _("UFC/mL"),
"label_Strains_QC_Not_Apply": _("Does not apply"),
"label_Strains_QC_Date" : _("Date"),
"label_Strains_QC_Lot": _("Lot"),
"label_Strains_QC_New_Test": _("Add new test"),
"label_Strains_QC_Used_Test": _("Used Test"),
"label_Strains_QC_Result": _("Result"),
"label_Strains_QC_Observations": _("Observations"),
"label_Strains_QC_Responsible": _("Responsible"),
"label_Strains_QC_Minimize": _("Minimize"),
"label_Strains_QC_Remove_Test": _("Remove test"),
"label_Strains_Stock_Lot_Number": _("Lot"),
"label_Strains_Stock_Minimum": _("Minimum Stock"),
"label_Strains_Stock_Preservation_Method": _("Preservation Method"),
"label_Strains_Stock_Total_Ampoules" : _("Total of available ampoules"),
"label_Strains_Stock_In_Stock": _("In Stock"),
"label_Strains_Security_Checkbox_Go_Catalog": _("This strain goes to catalog"),

#institutions
"label_Institutions_General_Code1": _("Code1"),
"label_Institutions_General_Code2": _("Code2"),
"label_Institutions_General_Code3": _("Code3"),
"label_Institutions_General_Locator": _("Locator"),
"label_Institutions_General_Name": _("Name"),
"label_Institutions_General_Address": _("Address"),
"label_Institutions_General_Phone": _("Phones/Fax"),
"label_Institutions_General_Email": _("Email"),
"label_Institutions_General_Website": _("Website"),
"label_Institutions_General_Comments": _("Comments"),
"label_Institutions_General_Complement": _("Complement"),
"label_Institutions_Security_Checkbox_Go_Catalog": _("This institution goes to catalog"),

#people
"label_People_Security_Checkbox_Go_Catalog": _("This people goes to catalog"),
"label_People_General_Nickname": _("NickName"),
"label_People_General_Name": _("Name"),
"label_People_General_Phone": _("Phones/Fax"),
"label_People_General_Comments": _("Comments"),
"label_People_General_Institution": _("Institution"),
"label_People_General_Personal_Address": _("Personal Address"),
"label_People_General_Personal_Email": _("Personal E-mail"),

#documents
"label_Documents_General_Code": _("Code"),
"label_Documents_General_Qualifier": _("Qualifier"),
"label_Documents_Gereral_Test_Category": _("Category"),
"label_Documents_General_Title": _("Title"),
"label_Documents_General_Description": _("Description"),
"label_Documents_General_File_Name": _("File Name"),
"label_Documents_General_Update_Insert_File" : _("Update/Insert File"),
"label_Documents_Security_Checkbox_Go_Catalog": _("This document goes to catalog"),

#references
"label_References_General_Code": _("Code"),
"label_References_General_Title": _("Title"),
"label_References_General_Comments": _("Comments"),
"label_References_General_Year":_("Year"),
"label_References_General_URL": _("URL"),
"label_References_General_Author": _("Author"),
"label_References_Security_Checkbox_Go_Catalog": _("This reference goes to catalog"),

#preservation
"label_Preservation_General_Strain_Code": _("Code"),
"label_Preservation_General_Responsible": _("Responsible"),
"label_Preservation_General_Lot_Number": _("Lot"),
"label_Preservation_General_Origin_Lot_Number": _("Lot"),
"label_Preservation_Strain_Origin_Position": _("Original Position"),
"label_Preservation_General_Used_Method": _("Used Method"),
"label_Preservation_Strain_Stock_Minimum_Abreviation": _("Min."),
"label_Preservation_Strain_Type": _("Preservation Type"),
"label_Preservation_General_Process_Data": _("Process Data"),
"label_Preservation_Strain_Macro_Characs": _("Macroscopic Characteristics"),
"label_Preservation_Strain_Micro_Characs": _("Microscopic Characteristics"),
"label_Preservation_Strain_Result": _("Results"),
"label_Preservation_Strain_Obs": _("Observations"),
"label_Preservation_Strain_Strain": _("Strain"),
"label_Preservation_Strain_Origin": _("Origin"),
"label_Preservation_Strain_Origin_Fieldset": _("Origin"),
"label_Preservation_Strain_Purity": _("Purity"),
"label_Preservation_Strain_Purity_Fieldset": _("Purity"),
"label_Preservation_Strain_Stock_Position": _("Stock Position"),
"label_Preservation_General_Preservation_Method_Fieldset": _("Preservation Method"),
"label_Preservation_Strain_Cryoprotector": _("Cryoprotector"),
"label_Preservation_Strain_Counting": _("Counting"),
"label_Preservation_Strain_Counting_Unity": _("UFC/mL"),
"label_Preservation_Strain_Not_Apply": _("Does not apply"),
"label_Preservation_Strain_Culture_Conditions" : _("Culture Conditions"),
"label_Preservation_Strain_Culture_Medium" : _("Culture Medium"),
"label_Preservation_Strain_Temperature" : _("Temperature"),
"label_Preservation_Strain_Decrease_Stock": _("Decrease Stock"),
"label_Preservation_Strain_Stock_Limit": _("Minimum Stock"),
"label_Preservation_General_Date" : _("Date"),
"label_Preservation_Strain_Incubation_Time" : _("Incubation Time"),
"label_Preservation_Strain_In_Stock": _("In Stock"),
"label_Preservation_General_Lot": _("Lot"),
"label_Preservation_Strain_Original_Location": _("Original Location"),
"label_Preservation_Strain_Maximize": _("Maximize"),
"label_Preservation_Strain_Minimize": _("Minimize"),
"label_Preservation_Strain_Remove_Strain": _("remove Strain"),
"label_Preservation_Strain_Add_New_Strain": _("add new Strain"),

#distribution
"label_Distribution_General_Responsible": _("Responsible"),
"label_Distribution_General_Lot_Number": _("Lot"),
"label_Distribution_General_Quantity": _("Qtty."),
"label_Distribution_General_Reason": _("Reason"),
"label_Distribution_General_Institution": _("Institution"),
"label_Distribution_General_Person": _("Person"),
"label_Distribution_General_Strain": _("Strain"),
"label_Distribution_General_Strain": _("Strain"),
"label_Distribution_General_Institution": _("Institution"),
"label_Distribution_General_Date" : _("Date"),

#configuration
"label_Configuration_Group_User": _("User"),
"label_Configuration_Users_Name": _("Name"),
"label_Configuration_Users_Login": _("Login"),
"label_Configuration_Users_Password": _("Password"),
"label_Configuration_Users_Password_Quality": _("Password quality"),
"label_Configuration_Users_Confirm_Password": _("Confirm password"),
"label_Configuration_Users_Comments": _("Comments"),
"label_Configuration_Users_Roles": _("Groups"),
"label_Configuration_Users_Create_Opt": _("Create"),
"label_Configuration_Users_Delete_Opt": _("Delete"),
"label_Configuration_Coll_Base":_("Base"),
"label_Configuration_Coll_Code":_("Code"),
"label_Configuration_Coll_Name":_("Name"),
"label_Configuration_Coll_Logo":_("Logo"),
"label_Configuration_Coll_Logo_Size":_("(130x30)"),
"label_Configuration_Division_Division": _("Division"),
"label_Configuration_Division_Pattern": _("Pattern"),
"label_Configuration_Role_Name": _("Name"),
"label_Configuration_Role_Description": _("Description"),
"label_Configuration_Role_Type": _("Type"),
"label_Configuration_Role_Modules": _("Modules"),
"label_Configuration_Role_Group": _("Group"),
"label_Configuration_Role_Level": _("Level"),
"label_Configuration_Role_Group_Members": _("Group Members"),
"label_Configuration_Subcoll_Coll":_("Collection"),
"label_Configuration_Subcoll_Name":_("Name"),
"label_Configuration_Subcoll_Code":_("Code"),
"label_Configuration_Subcoll_DateInput":_("Date Input Mask"),
"label_Configuration_Subcoll_DateOutput":_("Date Output Mask"),
"label_Configuration_Subcoll_Data_Lang": _("Input Language"),
"label_Configuration_Subcoll_Data_Lang_Associates": _("Associates"),
"label_Configuration_Subcoll_Data_Lang_Not_Associates": _("Not Associates"),
"label_Configuration_Subcoll_To_Associate_Data_Lang": _("To Associate"),
"label_Configuration_Subcoll_To_Dissociate_Data_Lang": _("To Dissociate"),
"label_Configuration_Subcoll_Move_Up_Data_Lang": _("Move Up"),
"label_Configuration_Subcoll_Move_Down_Data_Lang": _("Move Down"),
"label_Configuration_Subcoll_Lang":_("Language"),
"label_Configuration_Subcoll_Day":_("Day"),
"label_Configuration_Subcoll_Month":_("Month"),
"label_Configuration_Subcoll_Year":_("Year"),
"label_Configuration_Combos_Dep_Reason_Associates": _("Associates"),
"label_Configuration_Combos_Dep_Reason_Not_Associates": _("Not Associates"),
"label_Configuration_Combos_Move_Up_Dep_Reason": _("Move Up"),
"label_Configuration_Combos_Move_Down_Dep_Reason": _("Move Down"),
"label_Configuration_Combos_Str_Type": _("Strain - General - Type"),
"label_Configuration_Combos_Str_Type_Associates": _("Associates"),
"label_Configuration_Combos_Str_Type_Not_Associates": _("Not Associates"),
"label_Configuration_Combos_To_Associate_Str_Type": _("To Associate"),
"label_Configuration_Combos_To_Dissociate_Str_Type": _("To Dissociate"),
"label_Configuration_Combos_Move_Up_Str_Type": _("Move Up"),
"label_Configuration_Combos_Move_Down_Str_Type": _("Move Down"),
"label_Configuration_Combos_New_Item": _("New Item"),
"label_Configuration_Combos_Test_Group": _("Document - Test - Group"),
"label_Configuration_Combos_Test_Group_Associates": _("Associates"),
"label_Configuration_Combos_Test_Group_Not_Associates": _("Not Associates"),
"label_Configuration_Combos_To_Associate_Test_Group": _("To Associate"),
"label_Configuration_Combos_To_Dissociate_Test_Group": _("To Dissociate"),
"label_Configuration_Combos_Move_Up_Test_Group": _("Move Up"),
"label_Configuration_Combos_Move_Down_Test_Group": _("Move Down"),
"label_Configuration_Combos_Preservation_Method": _("Preservation Method / Unit of Measure"),
"label_Configuration_Combos_Preservation_Method_Associates": _("Associates"),
"label_Configuration_Combos_Preservation_Method_Not_Associates": _("Not Associates"),
"label_Configuration_Combos_To_Associate_Preservation_Method": _("To Associate"),
"label_Configuration_Combos_To_Dissociate_Preservation_Method": _("To Dissociate"),
"label_Configuration_Combos_Move_Up_Preservation_Method": _("Move Up"),
"label_Configuration_Combos_Move_Down_Preservation_Method": _("Move Down"),
"label_Configuration_Combos_Taxon_Group": _("Taxon Group"),
"label_Configuration_Combos_Taxon_Group_Associates": _("Associates"),
"label_Configuration_Combos_Taxon_Group_Not_Associates": _("Not Associates"),
"label_Configuration_Combos_To_Associate_Taxon_Group": _("To Associate"),
"label_Configuration_Combos_To_Dissociate_Taxon_Group": _("To Dissociate"),
"label_Configuration_Combos_Move_Up_Taxon_Group": _("Move Up"),
"label_Configuration_Combos_Move_Down_Taxon_Group": _("Move Down"),
"label_Configuration_Databases_Data": _("Databases Data"),
"label_Configuration_Databases_Data_Dbms":_("Data DBMS"),
"label_Configuration_Databases_Data_Host":_("Data Host"),
"label_Configuration_Databases_Data_Port":_("Data Port"),
"label_Configuration_Databases_Data_Name":_("Data Name"),
"label_Configuration_Databases_Data_User":_("Data User"),
"label_Configuration_Databases_Data_Pwd":_("Data Password"),
"label_Configuration_Databases_Tracebility": _("Database Tracebility"),
"label_Configuration_Databases_Tracebility_Dbms":_("Tracebility DBMS"),
"label_Configuration_Databases_Tracebility_Host":_("Tracebility Host"),
"label_Configuration_Databases_Tracebility_Port":_("Tracebility Port"),
"label_Configuration_Databases_Tracebility_Name":_("Tracebility Name"),
"label_Configuration_Databases_Tracebility_User":_("Tracebility User"),
"label_Configuration_Databases_Tracebility_Pwd":_("Tracebility Password"),
"label_Configuration_Config_IndexURL":_("Index URL"),
"label_Configuration_Config_RootDir":_("Root Directory"),
"label_Configuration_Config_StartPage":_("Start Page"),
"label_Configuration_Config_DateInput":_("Date Input Mask"),
"label_Configuration_Config_DateOutput":_("Date Output Mask"),
"label_Configuration_Config_Data_Lang": _("Input Language"),
"label_Configuration_Config_Data_Lang_Associates": _("Associates"),
"label_Configuration_Config_Data_Lang_Not_Associates": _("Not Associates"),
"label_Configuration_Config_To_Associate_Data_Lang": _("To Associate"),
"label_Configuration_Config_To_Dissociate_Data_Lang": _("To Dissociate"),
"label_Configuration_Config_Move_Up_Data_Lang": _("Move Up"),
"label_Configuration_Config_Move_Down_Data_Lang": _("Move Down"),
"label_Configuration_Config_Lang":_("Language"),
"label_Configuration_Config_Max_Upload_Size": _("Maximum upload size (bytes)"),
"label_Configuration_Config_Upload_Blank": _("Leave blank to disable size limit"),
"label_Configuration_Users_Subcollection": _("Subcollection"),
"label_Configuration_Division_Subcollection": _("Subcollection"),
"label_Configuration_Templates_Subcollection": _("Subcollection"),
"label_Configuration_Templates_select_subcoll": _("Select a Subcoll"),

#utilities - Stock Movement
"label_Traceability_Datetime": _("Date/Time"),
"label_Traceability_Datetime_To": _("to"),
"label_Traceability_User": _("User"),
"label_Traceability_Operation": _("Operation"),
"label_Traceability_Record": _("Record"),
"label_Traceability_Search": _("Search"),
"label_Traceability_Reset_Search": _("Reset Search"),
"label_Traceability_Strain_Code": _("Strain Code"),
"label_Traceability_Lot": _("Lot"),
"label_Traceability_Field": _("Field"),
"label_Traceability_Value": _("Value"),
"label_Traceability_Datetime": _("Date/Time"),
"label_Traceability_Datetime_To": _("to"),
"label_Traceability_User": _("User"),
"label_Traceability_Operation": _("Operation"),
"label_Traceability_Record": _("Record"),
"label_Traceability_Search": _("Search"),
"label_Traceability_Strain_Code": _("Strain Code"),
"label_Traceability_Lot": _("Lot"),
"label_Traceability_Field": _("Field"),
"label_Traceability_Value": _("Value"),
"label_Stock_Movement_Date": _("Date"),
"label_Stock_Movement_Description": _("Description"),
"label_Stock_Movement_Preservation_Method": _("Preservation Method"),
"label_Stock_Movement_From": _("Stock Movement From"),
"label_Stock_Movement_To": _("Stock Movement To"),
"label_Stock_Movement_Positions": _("Stock Movement Positions"),

#utilities - Container
"label_Container_Abbreviation": _("Abbreviation"),
"label_Container_Description": _("Description"),
"label_Container_Preservation_Method": _("Preservation Methods"),
"label_Container_Structure": _("Structure"),
"label_Container_New": _("New"),
"label_Container_Del": _("Del"),
"label_Container_Copy": _("Copy"),
"label_Container_Paste": _("Paste"),

#preferences
"label_Preferences_Account_User_Password": _("Leave blank to maintain previous password."),
"label_Preferences_Account": _("Account"),
"label_Preferences_Language": _("Language"),
"label_Preferences_User_Lines_Per_Page": _("Lines shown per page"),
"label_Preferences_User_Max_Num_Pages":_("Maximum number of pages"),
"label_Preferences_User_Show_Strain_Inactives": _("Show inactive strains"),
"label_Preferences_User_Name": _("Name"),
"label_Preferences_User_Login": _("Login"),
"label_Preferences_User_Password": _("Password"),
"label_Preferences_User_Confirm_Password": _("Confirm password"),
"label_Preferences_User_Roles": _("Groups"),

#login
"label_Login_User": _("User"),
"label_Login_Password": _("Password"),
"label_Login_Type_User_And_Password": _("Type your name user and password to enter."),
"label_Login_Type_User": _("Type your user name"),
"label_Login_Type_Password": _("Type your password"),
"label_Login_Enter": _("Enter"),

#logout
"label_Logout_Successfull_Title": _("Logged Out Successfully"),
"label_Logout_Successfull_Phrase": _("You have logged out correctly."),
"label_Logout_Login_Again": _("Login again"),

#subcollection
"label_Subcollection_Choose_Subcollection": _("Choose the subcolletion"),

#form.save
"label_Unknown_Error": _("An unknown error has occurred during operation."),
"label_Error_Contact": _("Contact the System Administrator and inform him the following message:"),
"label_Return_Error": _("Return to form and try again"),
"label_Operation_Error": _("Operation Error"),

#tests
"label_Javascript_Error": _("JavaScript Error"),
"label_JS_Error_Msg1": _("Your browser does not have JavaScript support or it is disabled."),
"label_JS_Error_Msg2": _("This feature is essential for some system features."),
"label_JS_Error_Msg3": _("Please verify your browser's JavaScript support, enable it and try again."),
"label_Cookie_Error": _("Cookie Error"),
"label_Cookie_Error_Msg1": _("Your browser does not have Cookies support or it is disabled."),
"label_Cookie_Error_Msg2": _("This feature is essential to use thise system."),
"label_Cookie_Error_Msg3": _("Please verify your browser's Cookie support, enable it and try again."),

#dynamics (don't remove)
"label_distribution_Locations": _("Origin Locations"),
"label_preservation_Locations": _("Stock Position"),
"label_quality_Locations": _("Origin Locations"),

#generic labels
"label_Version": _("Version"),
"label_Footer": _("Collection Information System of Biotechnological Interest, SICol"),
"label_Access_Denied": _("ACCESS DENIED!"),
"label_Location_Container": _("Container"),
"label_Location_Location": _("Location"),
"label_Location_ValorClique": _("Click Quantity"),
"label_Location_Yes": _("yes"),
"label_Location_No": _("no"),
"label_Print": _("PRINT"),
"label_Confirm_Delete": _("Do you really want to delete this item?"),
"label_Delete": _("DELETE"),
"label_Edit": _("EDIT"),
"label_SaveAs": _("SAVE_AS"),
"label_Permission": _("Permission"),
"label_Save": _("SAVE"),
"label_Cancel": _("CANCEL"),
"label_Filter": _("Filter"),
"label_OK": _("OK"),
"label_Do_Filter": _("Do Filter"),
"label_Textlink_Support": _("this field supports textLinks"),

#tinyMCE plugin
"textlink_Type" : _("TextLink Type"),
"textlink_Reference" : _("Reference"),
"textlink_Document" : _("Document"),
"textlink_Taxa" : _("Taxa"),
"textlink_Link" : _("Link"),
"textlink_Title" : _("Title"),
"textlink_Insert" : _("Insert"),
"textlink_Cancel" : _("Cancel"),

#menus
"menu_Strains": _("Strains"),
"menu_Species": _("plural|Species"),
"menu_People": _("People"),
"menu_Institutions": _("Institutions"),
"menu_Documents": _("Documents"),
"menu_References": _("References"),
"menu_Preservation": _("Preservation"),
"menu_Distribution": _("Distribution"),
"menu_Reports": _("Reports"),
"menu_Rep_General": _("General"),
"menu_Rep_Fields": _("Fields"),
"menu_Rep_Filters": _("Filters"),
"menu_Rep_Format": _("Format"),
"menu_Rep_Security": _("Security"),
"menu_Strains_Tip": _("Strains Tip"),
"menu_Species_Tip": _("Species Tip"),
"menu_People_Tip": _("People Tip"),
"menu_Institutions_Tip": _("Institutions Tip"),
"menu_Documents_Tip": _("Documents Tip"),
"menu_References_Tip": _("References Tip"),
"menu_Preferences": _("Preferences"),
"menu_Configuration": _("Configuration"),
"menu_Traceability": _("Traceability"),
"menu_Users": _("Users"),
"menu_Groups": _("Groups"),
"menu_Collections": _("Collections"),
"menu_Subcollections": _("Subcollections"),
"menu_Combos": _("Combos"),
"menu_Divisions": _("Divisions"),
"menu_Reports": _("Reports"),
"menu_Databases": _("Databases"),
"menu_ConfigXML": _("Config.xml"),
"menu_Strains_General_Tip": _("General Tip"),
"menu_Strains_Deposit_Tip": _("Deposit Tip"),
"menu_Strains_Collection_Event_Tip": _("Collection-Event Tip"),
"menu_Strains_Isolation_Tip": _("Isolation Tip"),
"menu_Strains_Identification_Tip": _("Identification Tip"),
"menu_Strains_Culture_Tip": _("Culture Tip"),
"menu_Strains_Characteristics_Tip": _("Characteristics Tip"),
"menu_Strains_Security_Tip": _("Security Tip"),
"menu_Distribution_General": _("General"),
"menu_Documents_General": _("General"),
"menu_Institutions_General": _("General"),
"menu_People_General": _("General"),
"menu_Preservation_General": _("General"),
"menu_References_General": _("General"),
"menu_Species_General": _("General"),
"menu_Strains_General": _("General"),
"menu_Reports_General": _("General"),
"menu_Strains_Deposit": _("Deposit"),
"menu_Strains_Collection_event": _("Collection-Event"),
"menu_Strains_Isolation": _("Isolation"),
"menu_Strains_Identification": _("Identification"),
"menu_Strains_Culture": _("Culture"),
"menu_Strains_Characteristics": _("Characteristics"),
"menu_Strains_Properties": _("Properties"),
"menu_Strains_Quality": _("Quality"),
"menu_Strains_Stock": _("Stock"),
"menu_Distribution_Security": _("Security"),
"menu_Documents_Security": _("Security"),
"menu_Institutions_Security": _("Security"),
"menu_People_Security": _("Security"),
"menu_Preservation_Security": _("Security"),
"menu_References_Security": _("Security"),
"menu_Species_Security": _("Security"),
"menu_Strains_Security": _("Security"),
"menu_Reports_Security": _("Security"),
"menu_Stockmovement": _("Stock Movement"),
"menu_Containers": _("Containers"),
"menu_Traceability": _("Traceability"),

#links
"link_Preferences": _("Preferences"),
"link_Configuration": _("Configuration"),
"link_Utilities": _("Utilities"),
"link_Exit": _("Exit"),
"link_Exit_Title": _("Choose other Subcollection or Exit"),
"link_Logout": _("Logout"),
"link_New": _("New"),
"link_Reports": _("Reports"),
"link_Search": _("Search"),
"link_Advanced_Search": _("Advanced Search"),
"link_Include_New": _("Include New"),

#reports
"label_Rep_ID" : _("ID"),
"label_Rep_General_Type" : _("Type"),
"label_Rep_General_Description" : _("Description"),
"label_Rep_General_Select" : _("Selected"),
"label_Rep_General_Group" : _("Group by"),
"label_Rep_General_Order" : _("Order by"),
"label_Rep_General_Totalizer" : _("Totalized by"),
"label_Rep_General_Filter" : _("Filter"),
"label_Rep_General_Report_Format": _("Report format"),
"label_Rep_Language" : _("Language"),
"label_Rep_Language_Values" : _ ("Use fields content in"),

"label_Rep_Format": _("Format"),
"label_Rep_Default_HTML": _("Default HTML"),
"label_Rep_Default": _("Default HTML"),
"label_Rep_default": _("Default HTML"),
"label_Rep_CSV": _("CSV"),
"label_Rep_csv": _("CSV"),
"label_Rep_Chart": _("Chart"),
"label_Rep_chart": _("Chart"),
"label_Rep_Custom_HTML": _("Custom HTML"),
"label_Rep_Custom": _("Custom HTML"),
"label_Rep_custom": _("Custom HTML"),
"label_Rep_XML": _("XML"),
"label_Rep_xml": _("XML"),

"label_Rep_page_title":_("SICol - Report"),

"label_Rep_Header": _("Header"),
"label_Rep_External": _("External"),
"label_Rep_Internal": _("Internal"),
"label_Rep_None": _("None"),

"label_Rep_Separator": _("Separator"),

"label_Rep_chart_type": _("Chart Type"),
"label_Rep_Bar": _("Bar"),
"label_Rep_Pie": _("Pie"),
"label_Rep_Line": _("Line"),
"label_Rep_Column": _("Column"),

"label_Rep_header_template": _("Header template"),
"label_Rep_footer_template": _("Footer template"),
"label_Rep_data_template": _("Data template"),
"label_Rep_css_template": _("CSS template"),

"label_Rep_subcoll_template": _("Use SubColl Templates"),
"label_Rep_header": _("Header Template"),
"label_Rep_footer": _("Footer Template"),

"label_Rep_fieldlink_Type" : _("FieldLink Type"),
"label_Rep_System_Fields" : _("System Fields"),
"label_Rep_Report_Fields" : _("Report Fields"),
"label_Rep_fieldlink_Insert" : _("Insert"),
"label_Rep_fieldlink_Cancel" : _("Cancel"),
"label_Rep_Date" : _("Date"),
"label_Rep_Time" : _("Time"),
"label_Rep_Name_Coll" : _("Collection Name"),
"label_Rep_Code_Coll" : _("Collection Code"),
"label_Rep_Name_Subcoll" : _("Subcollection Name"),
"label_Rep_Code_Subcoll" : _("Subcollection Code"),
"label_Rep_User" : _("User Name"),
"label_Rep_Description" : _("Report Description"),
"label_Rep_totalizer" : _("Total"),

"label_Rep_equal": _("Equals"),
"label_Rep_differs": _("Differs"),
"label_Rep_contains": _("Contains"),
"label_Rep_in": _("In"),
"label_Rep_not_in": _("Not In"),
"label_Rep_greater": _("Greater"),
"label_Rep_greater_or_equal": _("Greater or Equal"),
"label_Rep_less": _("Less"),
"label_Rep_less_or_equal": _("Less or Equal"),

"label_Rep_connector_and" : _("and"),
"label_Rep_connector_or"  : _("or"),
"label_Rep_connector_"    : "",

#strain reports fields

"label_Rep_Strain_Id": _("Strain ID"),
"label_Rep_Division": _("Division"),
"label_Rep_Code": _("Code"),
"label_Rep_Numeric_Code": _("Number"),
"label_Rep_Origin_Code": _("Origin Code"),
"label_Rep_Status": _("Status"),
"label_Rep_Taxon_Group": _("Taxon Group"),
"label_Rep_Taxon": _("Taxon"),
"label_Rep_Type": _("Type"),
"label_Rep_Name": _("Name"),
"label_Rep_Description": _("Description"),
"label_Rep_Next": _("Next"),
"label_Rep_Fields": _("Fields"),
"label_Rep_Selected": _("Selected"),
"label_Rep_Group": _("Group"),
"label_Rep_Totaled": _("Totalized"),
"label_Rep_Step1": _("Step1"),
"label_Rep_Step2": _("Step2"),
"label_Rep_Is_Ogm": _("Is Ogm"),
"label_Rep_Taxonomic_Complement": _("Taxonomic Complement"),
"label_Rep_History": _("History"),
"label_Rep_Other_Codes": _("Other Codes"),
"label_Rep_General_Comments": _("General Comments"),
"label_Rep_Collect_Date": _("Collect Date"),
"label_Rep_Collect_Year": _("Collect Year"),
"label_Rep_Collect_Month": _("Collect Month"),
"label_Rep_Collect_Person": _("Collect Person"),
"label_Rep_Collect_Institution": _("Collect Institution"),
"label_Rep_Country": _("Country"),
"label_Rep_State_Code": _("State Code"),
"label_Rep_State_Name": _("State Name"),
"label_Rep_City": _("City"),
"label_Rep_Place": _("Place"),
"label_Rep_Latitude": _("Latitude"),
"label_Rep_Latitude_DMS": _("Latitude DMS"),
"label_Rep_Latitude_Mode": _("Latitude Mode"),
"label_Rep_Longitude": _("Longitude"),
"label_Rep_Longitude_DMS": _("Longitude DMS"),
"label_Rep_Longitude_Mode": _("Longitude Mode"),
"label_Rep_Datum": _("Datum"),
"label_Rep_GPS_Precision": _("GPS Precision"),
"label_Rep_GPS_Comments": _("GPS Comments"),
"label_Rep_Substratum": _("Substratum"),
"label_Rep_Host_Name": _("Host Name"),
"label_Rep_Host_Genus": _("Host Genus"),
"label_Rep_Host_Species": _("Host Species"),
"label_Rep_Host_Level": _("Host Level"),
"label_Rep_Host_Subspecies": _("Host Subspecies"),
"label_Rep_Host_Taxonomic_Complement": _("Host Taxonomic Complement"),
"label_Rep_International_Code": _("International Code"),
"label_Rep_Clinical_Form_Code": _("Clinical Form Code"),
"label_Rep_Clinical_Form_Name": _("Clinical Form Name"),
"label_Rep_HIV": _("HIV"),
"label_Rep_Collect_Comments": _("Collect Comments"),
"label_Rep_Isolation_Date": _("Isolation Date"),
"label_Rep_Isolation_Year": _("Isolation Year"),
"label_Rep_Isolation_Month": _("Isolation Month"),
"label_Rep_Isolation_Person": _("Isolation Person"),
"label_Rep_Isolation_Institution": _("Isolation Institution"),
"label_Rep_Isolation_From": _("Isolation From"),
"label_Rep_Isolation_Method": _("Isolation Method"),
"label_Rep_Isolation_Comments": _("Isolation Comments"),
"label_Rep_Identification_Date": _("Identification Date"),
"label_Rep_Identification_Year": _("Identification Year"),
"label_Rep_Identification_Month": _("Identification Month"),
"label_Rep_Identification_Person": _("Identification Person"),
"label_Rep_Identification_Institution": _("Identification Institution"),
"label_Rep_Identification_Genus": _("Identification Genus"),
"label_Rep_Identification_Species": _("Identification Species"),
"label_Rep_Identification_Level": _("Identification Level"),
"label_Rep_Identification_Subspecies": _("Identification Subspecies"),
"label_Rep_Identification_Taxonomic_Complement": _("Identification Taxonomic Complement"),
"label_Rep_Identification_Method": _("Identification Method"),
"label_Rep_Identification_Comments": _("Identification Comments"),
"label_Rep_Deposit_Date": _("Deposit Date"),
"label_Rep_Deposit_Year": _("Deposit Year"),
"label_Rep_Deposit_Month": _("Deposit Month"),
"label_Rep_Deposit_Person": _("Deposit Person"),
"label_Rep_Deposit_Institution": _("Deposit Institution"),
"label_Rep_Deposit_Genus": _("Deposit Genus"),
"label_Rep_Deposit_Species": _("Deposit Species"),
"label_Rep_Deposit_Level": _("Deposit Level"),
"label_Rep_Deposit_Subspecies": _("Deposit Subspecies"),
"label_Rep_Deposit_Taxonomic_Complement": _("Deposit Taxonomic Complement"),
"label_Rep_Deposit_Reason": _("Deposit Reason"),
"label_Rep_Deposit_Form": _("Deposit Form"),
"label_Rep_Recommended_Preservation_Method": _("Recommended Preservation Method"),
"label_Rep_Authentication_Date": _("Authentication Date"),
"label_Rep_Authentication_Year": _("Authentication Year"),
"label_Rep_Authentication_Month": _("Authentication Month"),
"label_Rep_Authentication_Person": _("Authentication Person"),
"label_Rep_Authentication_Result": _("Authentication Result"),
"label_Rep_Deposit_Comments": _("Deposit Comments"),
"label_Rep_Recommended_Growth_Medium": _("Recommended Growth Medium"),
"label_Rep_Recommended_Temperature": _("Recommended Temperature"),
"label_Rep_Incubation_Time": _("Incubation Time"),
"label_Rep_PH": _("PH"),
"label_Rep_Oxygen_Requirements": _("Oxygen Requirements"),
"label_Rep_Growth_Comments": _("Growth Comments"),
"label_Rep_Morphological_Characteristics": _("Morphological Characteristics"),
"label_Rep_Molecular_Characteristics": _("Molecular Characteristics"),
"label_Rep_Biochemical_Characteristics": _("Biochemical Characteristics"),
"label_Rep_Immunologic_Characteristics": _("Immunologic Characteristics"),
"label_Rep_Pathogenic_Characteristics": _("Pathogenic Characteristics"),
"label_Rep_Genotypic_Characteristics": _("Genotypic Characteristics"),
"label_Rep_OGM": _("OGM Group"),
"label_Rep_OGM_Comments": _("OGM Comments"),
"label_Rep_Biorisk_Comments": _("Biorisk Comments"),
"label_Rep_Restrictions": _("Restrictions"),
"label_Rep_Pictures": _("Pictures"),
"label_Rep_Characteristics_References": _("Characteristics References"),
"label_Rep_Catalogue_Notes": _("Catalogue Notes"),
"label_Rep_Properties": _("Properties"),
"label_Rep_Applications": _("Applications"),
"label_Rep_Properties_References": _("Properties References"),
"label_Rep_Go_Catalog": _("Go Catalog"),

"label_Rep_Inst_ID": _("Institution ID"),
"label_Rep_Inst_Code1": _("Code1"),
"label_Rep_Inst_Code2": _("Code2"),
"label_Rep_Inst_Code3": _("Code3"),
"label_Rep_Inst_Complement": _("Complement"),
"label_Rep_Inst_Nickname": _("Locator"),
"label_Rep_Inst_Name": _("Name"),
"label_Rep_Inst_Address": _("Address"),
"label_Rep_Inst_Phone": _("Phones/Fax"),
"label_Rep_Inst_Email": _("Email"),
"label_Rep_Inst_Website": _("Website"),
"label_Rep_Inst_Go_Catalog": _("Go Catalog"),
"label_Rep_Inst_Comments": _("Comments"),

"label_Rep_Per_ID": _("Person ID"),
"label_Rep_Per_Name": _("Name"),
"label_Rep_Per_Nickname": _("NickName"),
"label_Rep_Per_Address": _("Address"),
"label_Rep_Per_Phone": _("Phones/Fax"),
"label_Rep_Per_Email": _("Email"),
"label_Rep_Per_Go_Catalog": _("Go Catalog"),
"label_Rep_Per_Comments": _("Comments"),

"label_Rep_Doc_ID": _("Document ID"),
"label_Rep_Doc_Code": _("Code"),
"label_Rep_Doc_Qualifier": _("Qualifier"),
"label_Rep_Doc_Title": _("Title"),
"label_Rep_Doc_Description": _("Description"),
"label_Rep_Doc_File_Name": _("File Name"),
"label_Rep_Doc_Category": _("Category"),
"label_Rep_Doc_Go_Catalog": _("Go Catalog"),

"label_Rep_Ref_Code": _("Code"),
"label_Rep_Ref_Title": _("Title"),
"label_Rep_Ref_Author": _("Author"),
"label_Rep_Ref_Year": _("Year"),
"label_Rep_Ref_Url": _("URL"),
"label_Rep_Ref_Comments": _("Comments"),
"label_Rep_Ref_Go_Catalog": _("Go Catalog"),

"label_Rep_Spe_ID": _("Taxon ID"),
"label_Rep_Spe_Taxon_Group": _("Taxonomic Group"),
"label_Rep_Spe_Hi_Tax": _("Higher Taxa"),
"label_Rep_Spe_Sciname": _("Scientific Name"),
"label_Rep_Spe_Sciname_No_Auth": _("Scientific Name No Auth"),
"label_Rep_Spe_Taxon_Ref": _("Taxonomic References"),
"label_Rep_Spe_Synonym": _("Synonym"),
"label_Rep_Spe_Hazard_Group": _("Hazard_Group"),
"label_Rep_Spe_Hazard_Group_Ref": _("Hazard Group Reference"),
"label_Rep_Spe_Ambient_Risk": _("Hazard Group Comments"),
"label_Rep_Spe_Sciname_Alt_State": _("Alternative State"),
"label_Rep_Spe_Alt_States_Type": _("Alternative State Type"),
"label_Rep_Spe_Comments": _("Comments"),

"label_Rep_Stock_Strain_Code": _("Strain (Code)"),
"label_Rep_Stock_Strain_Numeric_Code": _("Strain (Number)"),
"label_Rep_Stock_Taxon": _("Taxon"),
"label_Rep_Stock_Preservation_Method": _("Preservation Method"),
"label_Rep_Stock_Lot": _("Lot"),
"label_Rep_Stock_Position": _("Position"),
"label_Rep_Stock_Quantity": _("Quantity"),

#Report Generation Errors

"label_Rep_Generation_Error": _("Error in Report Generation"),
"label_Rep_Return_List": _("Return to Reports List"),


}

